- name: Docker, Node, Npm installation
  hosts: vps
  become: yes

  tasks:
  - name: Update apt
    ansible.builtin.apt:
      update_cache: yes

  - name: Install required packages
    ansible.builtin.apt:
      name: 
        - docker.io
        - docker-compose
        - nodejs
        - npm
      state: present